baseURL = "https://www.evankurzman.com/"
languageCode = "en-us"
title = "Evan Kurzman"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Evan Kurzman"
    description = "enjoy!"
    githubUsername = "thekurz"
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["python", "ocaml", "R", "java", "VBA"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

[[menu.main]]
    url = "/media/"
    name = "Media"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:ehk73@cornell.edu"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/thekurz/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/thekurzzz/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/evan-kurzman-cfa-fdp/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.instagram.com/eekurz/"
    name = "fab fa-instagram"
    weight = 5

[[menu.icon]]
    url = "https://vimeo.com/jerzzz"
    name = "fab fa-vimeo"
    weight = 5